Fix bootstrap mode problem (no default initramfs created).

diff --git a/src/bootstrap b/src/bootstrap
--- a/src/bootstrap
+++ b/src/bootstrap
@@ -112,7 +112,7 @@ log "Creating EFI filesystem"
 mkfs.fat -F32 "$efi_part"
 
 log "Creating swap filesystem"
-mkswap -F32 "$swap_part"
+mkswap "$swap_part"
 
 log "Creating root filesystem"
 # TODO: replace with ZFS
@@ -145,12 +145,12 @@ log "Copying bootstrap initramfs to root..."
 rsync -W -a -x --human-readable / /sysroot/ 2>&1 || fatal 1 "Failed copying OS to /sysroot"
 
 log "Ensure efi dir exists..."
-mkdir -p /boot/efi
+mkdir -p /sysroot/boot/efi
 
 log "Writing /etc/fstab ..."
 # TODO: fix this if we change root partitioning above
-echo "UUID=${root_uuid}     /   ext4    defaults,noatime    0   0" > /sysroot/etc/fstab
-echo "UUID=${efi_uuid}      /boot/efi   defaults,noatime    0   0" >> /sysroot/etc/fstab
+echo "UUID=${root_uuid}     /           ext4    defaults,noatime,discard    0   0" > /sysroot/etc/fstab
+echo "UUID=${efi_uuid}      /boot/efi   vfat    defaults,noatime,discard    0   0" >> /sysroot/etc/fstab
 echo "UUID=${swap_uuid}     none        swap                0   0" >> /sysroot/etc/fstab
 
 log "Converting initrd to os..."
@@ -159,23 +159,26 @@ mv /sysroot/etc/initrd-release /sysroot/etc/os-release || fatal 1 "Failed moving
 log "Making machine-id permanent..."
 systemd-machine-id-setup --commit --root=/sysroot || fatal 1 "Could not set machine-id on new root."
 
-#if [ -d /sys/firmware/efi ] ; then
-#    log "Installing EFI grub"
-#    
-#else
-#    log "Installing BIOS grub"
-#    grub-install --root=/sysroot ${target_device} || fatal 1 "grub-install failed."
-#fi
+if [ -d /sys/firmware/efi ] ; then
+    log "Installing EFI grub"
+    grub-install --root=/sysroot --efi-directory=/sysroot/boot/efi ${target_device} || fatal 1 "grub-install failed."    
+else
+    log "Installing BIOS grub"
+    grub-install --root=/sysroot ${target_device} || fatal 1 "grub-install failed."
+fi
 
-#mount --bind /dev /sysroot/dev
-#mount --bind /sys /sysroot/sys
-#mount --bind /proc /sysroot/proc
+mount --bind /dev /sysroot/dev
+mount --bind /sys /sysroot/sys
+mount --bind /proc /sysroot/proc
 
-#chroot /sysroot /usr/sbin/update-grub
+log "Generate initramfs for new system..."
+chroot /sysroot update-initramfs -c -k $(uname -r) || fatal 1 "Create initramfs failed."
+log "Update Grub..."
+chroot /sysroot /usr/sbin/update-grub || fatal 1 "Update grub failed."
 
-#umount /sysroot/dev
-#umount /sysroot/sys
-#umount /sysroot/proc
+umount /sysroot/dev
+umount /sysroot/sys
+umount /sysroot/proc
 
 log "Cleaning up bootstrap specific files on root..."
 source /bootstrap_cleanup
