More robust partition targeting.

diff --git a/src/bootstrap b/src/bootstrap
--- a/src/bootstrap
+++ b/src/bootstrap
@@ -65,15 +65,18 @@ sgdisk -o -n 1:0:+1M -n 2:0:0 -t 1:ef02 -t 2:8300 -c 1:"grub" ${target_device} |
 log "Reload partition tables..."
 blockdev --rereadpt "${target_device}" || fatal 1 "Could not re-read partition tables."
 
+log "Get target partition..."
+target_part=$(lsblk -rpn -oTYPE,NAME "${target_device}" | grep '^part ' | cut -d' ' -f2 | sed '2q;d')
+
 log "Creating root filesystem"
 # TODO: replace with ZFS
-mkfs.ext4 ${target_device}2 || fatal 1 "Could not create root filesystem."
+mkfs.ext4 "${target_part}" || fatal 1 "Could not create root filesystem."
 
 log "Reading the root UUID (note: set by filesystem, not GPT)"
-root_uuid=$(blkid -o value -s UUID "${target_device}2")
+root_uuid=$(blkid -o value -s UUID "${target_part}")
 
 log "Mounting root filesystem"
-mount ${target_device}2 /sysroot || fatal 1 "Could not mount new root filesystem."
+mount "${target_part}" /sysroot || fatal 1 "Could not mount new root filesystem."
 
 # Set bootstrap root password if requested.
 if [ ! -z "${bootstrap_root_password}" ]; then
